### ISSUE TITLE
Reordering files doesn't seem to work properly (--reorderFiles)

### ISSUE THREAD

**Issue by Janne252** [domchen/typescript-plus#1]
Hey,

I'm having issues with this compiler as it doesn't seem work properly. The files are reordered _a bit_ yet it still doesn't seem to work - I'm still getting the annoying `TypeError: Cannot read property 'prototype' of undefined` error.

The source code of my project can be found here: [github.com/Janne252/jannengine](https://github.com/Janne252/jannengine)

I'm using the following command to compile the project: 
`tsc-plus -p "tsconfig.json" --reorderFiles` (_Executed in the folder where the project's `index.html` is located_)

The generated `.js` seems to have a somewhat proper order but not entirely. I've also tried
 `/// <reference path="..." />` directives. They seem to be properly defined but for whatever reason the default TypeScript compiler seems to **ignore** them. 

Thank you for your work so far. I hope you can assist me with this.

**Comment by Janne252** [comment]
Fixed, for reference please see https://github.com/Microsoft/TypeScript/issues/12395

**Comment by domchen** [comment]
@Janne252 Sorry for taking so long to reply, I didn't notice the notifications from github. If you still have any problem of reordering files, feel free to let me know.  :)
