### ISSUE TITLE
circularReferences

### ISSUE THREAD

**Issue by whaqzhzd** [domchen/typescript-plus#12]
循环依赖好像检查检查不到
[ak47.zip](https://github.com/domchen/typescript-plus/files/2266530/ak47.zip)

**Comment by domchen** [comment]
最近加班比较凶，一周上七天。。。我先记下来，有时间来看一下。

**Comment by whaqzhzd** [comment]
加油

**Comment by domchen** [comment]
@whaqzhzd 你好，终于有时间看一下问题了，抱歉这么久才反馈。我仔细看了一下你提供的代码。这里是概念理解上有点偏差。tsc-plus的自动排序功能解决的是加载JS文件过程中的依赖问题，由于JS具有边加载边执行的能力，所以才会有这个加载顺序和依赖分析的需求。而你提供的代码里，虽然A的构造函数里引用了B，B的构造函数里引用了A。但是并没有任何地方触发了加载过程中立即实例化A或B的代码。也就是你的循环依赖本身是不存在的。代码能够安全加载不报错。你可以简单改一下。把new A()声明到一个静态变量上。命令行就会立马报循环依赖的错误了。这个层面上说，这个例子其实是一种逻辑错误。这个实际上是无法做到准确检查的，因为这个跟递归调用其实是一个道理。如果递归调用的截止条件是由运行时外部参数决定的，那一个正常的递归其实也可能无限循环不停止。工具上能避免的只是加载过程的中的依赖关系是否正确。逻辑的正确性要自己去判断。
