### ISSUE TITLE
某些情况下静态成员的依赖似乎有问题

### ISSUE THREAD

**Issue by saintEvol** [domchen/typescript-plus#13]
您好，首先感谢您提供的编译器，可以预见我们的项目中将会减少很多丑陋的三斜杠语法
但在我的测试项目中，目前发现某些情况下静态成员方法的依赖分析有时似乎存在问题，附件中是报错信息及相关源代码
![image](https://user-images.githubusercontent.com/28743628/47060328-c5312c80-d1ff-11e8-9bb3-2d49a5779671.png)

[sorterTest.zip](https://github.com/domchen/typescript-plus/files/2485777/sorterTest.zip)

**Comment by domchen** [comment]
收到，我周末看一下，最近一直在加班。。。

**Comment by saintEvol** [comment]
好的，先谢谢了



casle_death@163.com
 
发件人： Dom Chen
发送时间： 2018-10-23 14:59
收件人： domchen/typescript-plus
抄送： saintEvol; Author
主题： Re: [domchen/typescript-plus] 某些情况下静态成员的依赖似乎有问题 (#13)
收到，我周末看一下，最近一直在加班。。。

**Comment by domchen** [comment]
@saintEvol 感谢反馈，问题已经修复~ 不是静态属性依赖的问题，是因为这种写法：inject(C)(C, "test"); 直接执行一个函数返回的匿名函数，这种语法没覆盖到，需要继续分析返回的那个那个匿名函数内部的执行代码。请升级到2.7.4版本即可解决该问题。

**Comment by saintEvol** [comment]
好的，感谢处理，我再测试下



casle_death@163.com
 
发件人： Dom Chen
发送时间： 2018-10-28 20:03
收件人： domchen/typescript-plus
抄送： saintEvol; Mention
主题： Re: [domchen/typescript-plus] 某些情况下静态成员的依赖似乎有问题 (#13)
@saintEvol 感谢反馈，问题已经修复~ 不是静态属性依赖的问题，是因为这种写法：inject(C)(C, "test"); 直接执行一个函数返回的匿名函数，这种语法没覆盖到，需要继续分析返回的那个那个匿名函数内部的执行代码。请升级到2.7.4版本即可解决该问题。
