### ISSUE TITLE
继承关系中的依赖分析问题

### ISSUE THREAD

**Issue by saintEvol** [domchen/typescript-plus#14]
您好，感谢修复 #13 中的问题。
经过测试，发现当存在继承关系时，某些情况下，依赖分析似乎仍然存在问题：
![image](https://user-images.githubusercontent.com/28743628/47639134-81450c80-db9b-11e8-8690-d53d6b995898.png)
![image](https://user-images.githubusercontent.com/28743628/47639153-8c983800-db9b-11e8-8f75-3f3e3862ef53.png)
![image](https://user-images.githubusercontent.com/28743628/47639166-9883fa00-db9b-11e8-9d34-66f829d63f84.png)
附件中为相关代码。
[sorterTest.zip](https://github.com/domchen/typescript-plus/files/2524529/sorterTest.zip)

**Comment by saintEvol** [comment]
我推测可能和继承无直接关系，应该是下图中红框内的代码（入口类）载入顺序不正确
![image](https://user-images.githubusercontent.com/28743628/47640661-05e55a00-db9f-11e8-809f-8d69c0919dfc.png)

**Comment by domchen** [comment]
看起来是因为子类方法覆盖的问题，分析语法的时候确实没有覆盖到子类对应覆盖父类方法的隐式调用。这个改起来看起来工作量不小。可能也得周末看看了。

**Comment by domchen** [comment]
仔细想了一下，找到了简洁的解决思路，已经修复，更新到3.1.5版本即可。
