### ISSUE TITLE
编译异常提示疑问

### ISSUE THREAD

**Issue by zhangyouyuan** [domchen/typescript-plus#16]
编译 环境 tsc -v   Version 3.2.1
在tsconfig.json 里配置 module为 commonjs,有outFile属性 编译是可以成功把所有的ts编译成一个js文件,但是会提示outFile属性 Only 'amd' and 'system' modules are supported alongside --outFile
这种情况 在egret原生编译环境下是不会存在的.请大佬解答~

**Comment by domchen** [comment]
错误提示很明确了，按提示在tsconfig.json里加上如下配置就行：
"compilerOptions": {
    "module": "amd"
}
