### ISSUE TITLE
这个要怎么升级最新版的tsc

### ISSUE THREAD

**Issue by WangPengJu** [domchen/typescript-plus#17]

**Comment by eos3tion** [comment]
@WangPengJu 自己合并 microsoft/typescript 上的代码  
https://github.com/egret-labs/egret-core/pull/302  
白鹭那边的tsc，我都自己合并的

**Comment by WangPengJu** [comment]
@eos3tion  是整个仓库合并吗？

**Comment by eos3tion** [comment]
是的，由于dom-chen不是直接fork的microsoft/typescript，所以你自行fork最新的microsoft/typescript，然后把这个项目的改动部分，主要是ts-plus和checker的改动弄过去，执行gulp local编译tsc即可

**Comment by WangPengJu** [comment]
能否加一下我，QQ：19352226。 下午尝试了一下，没能正确合并。版本跨度有点大。

**Comment by WangPengJu** [comment]
@eos3tion 
能否加一下我，QQ：19352226。 下午尝试了一下，没能正确合并。版本跨度有点大。

**Comment by WangPengJu** [comment]
@eos3tion  我直接fork你的仓库了

**Comment by eos3tion** [comment]
@WangPengJu 我一般大版本才更新一下，也不会经常更新的。后面可能我会弃用dom-chen这套，改成用es6 module，用webpack打包。

**Comment by WangPengJu** [comment]
@eos3tion 你现在merger一次 需要修改地方会多吗

**Comment by eos3tion** [comment]
@WangPengJu microsoft/typescript之前做过几次 breaking change，是需要对dom chen的代码做修改的。你可以看我的修改记录。你把这个issue关了吧。
