### ISSUE TITLE
Resolving recursions fails with reorderFiles: true

### ISSUE THREAD

**Issue by dtg-wtf** [domchen/typescript-plus#2]
When the code to be compiled uses recursion itself, the **reorderFiles** option causes the transpiler to run into a infinite loop until the stack exceeds its limits.

$ tsc-plus -v
Version : 2.1.13
typescript-version : 2.1.4

**tsconfig.json**:
```
{
    "compilerOptions": {
        "outFile": "recursion-bug-test.js",
        "reorderFiles": true
    },
    "files": [
        "./recursion-bug-test.ts"
    ]
}
```
**recursion-bug-test.ts**:
```
class Foo {
    
    private x = 0;
    
    loop() {
        console.info('Loop #', this.x)
        
        if (this.x++ < 10) {
            this.loop();
        }
    }
}

new Foo().loop()
```

$ tsc-plus -p tsconfig.json

*RangeError: Maximum call stack size exceeded*

**Comment by domchen** [comment]
@dtg-wtf It is fixed now. Thanks for providing the test case.
