### ISSUE TITLE
config.json里配置的东西能不能支持从"extends": "base"取

### ISSUE THREAD

**Issue by naturtle** [domchen/typescript-plus#4]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**base.json**

```ts
{
    "compilerOptions": {
        "defines":{
            "DEBUG":true
        }
    }
}
```

**tsconfig.json**

```ts
{
    "extends": "base"
}
```

**Comment by domchen** [comment]
你可以试试这个项目：https://github.com/domchen/tspack 它是对typescript-plus的二次封装，提供了modules关键字在让你能在一个tsconfig.json里配置多个模块输出目标。公共的compilerOptions就是你这里的base的作用，每个module里还可以单独配置自己的编译参数覆盖全局的。

**Comment by naturtle** [comment]
啊，你还整了另一个啊，我看看

**Comment by domchen** [comment]
@naturtle 是的，因为这个功能不应该属于要修改编译器本身的，只是一个外部扩展而已。
