### ISSUE TITLE
Option to export reorderFiles result to tsconfig.json files

### ISSUE THREAD

**Issue by nbransby** [domchen/typescript-plus#5]
Would it be possible to add a flag to get tsc-plus to output the correct order of the input files to the console in a format that can be copied into the files property of a tsconfig.json?

Im finding it hard to develop in VSCode with tsc-plus as the TypeScript service cannot operate due to the incorrect file order, would be good to export the correct order from tsc-plus so I can get it working also

**Comment by domchen** [comment]
Yes, It is can be done by simply passing the --listFiles argument to command-line tool or add "listFiles": true to the compilerOptions in tsconfig.json file. Then you can get the correct order of input files in the console.
