### ISSUE TITLE
装饰器导致的依赖关系发生问题

### ISSUE THREAD

**Issue by whaqzhzd** [domchen/typescript-plus#6]
装饰器是一个专门的ts文件，里面写入了一系列js代码用export function。然后在ts文件中使用这些导出的js function。结果依赖关系发生混乱

**Comment by domchen** [comment]
@whaqzhzd 请给一个用于测试的示例文件，以及具体的报错信息，提供的信息太少无法定位具体问题是什么。

**Comment by domchen** [comment]
@whaqzhzd 请问你遇到的问题是已经解决了吗？

**Comment by domchen** [comment]
最后发现是因为tsc版本升级后对文件是否含有装饰器的标志位不能从文件本身查询到了，必须到类定义上查询。已经修复。
