### ISSUE TITLE
得到ts排序的接口有公开么？

### ISSUE THREAD

**Issue by ydcoming** [domchen/typescript-plus#7]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by domchen** [comment]
## 命令行方式

开启reorderFiles参数后，再在命令行加上参数--listFiles，就会从控制台打印出排序后的文件列表。

## 编程方式

排序的模块是独立的接口, 引用typescript.d.ts 就行

```
declare namespace ts {
    interface SortingResult {
        sortedFileNames: string[];
        circularReferences: string[];
    }
    function reorderSourceFiles(program: Program): SortingResult;
}

```
具体如何编程方式调用tsc，需要先去参考ts官方的API使用文档：[Using the Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API), 根据那边的文档构建出一个program对象，然后调用对program对象调用一次 ts.reorderSourceFiles(), 打印返回结果SortingResult.sortedFileNames 就行了。这部分的调用代码也可以参考本项目里 src/compiler/tsc.ts 内的compile() 函数内容。
