### ISSUE TITLE
 Unknown compiler option 'reorderFiles'.

### ISSUE THREAD

**Issue by etay-schur-sp** [domchen/typescript-plus#8]
After I installed the Plugin , I'm getting error message every time I try to compile : 
" Unknown compiler option 'reorderFiles'. "

Do you have any idea why I'm getting this error ?

thanks
Etay

**Comment by domchen** [comment]
How do you run it exactly? It is not a plugin, it is a complete replacement of tsc, you should run `tsc-pls [options]` instead of `tsc [options]` in the command line. Pls try again, let me know if you still have any problem. :)

**Comment by domchen** [comment]
@etay-schur-sp Sorry for the late reply, I was on vacation for last 12 days.
